included:
  - "Targets"
  
excluded:
  - "**/*.generated.swift"
  - "**/Derived"
  - ".build"
  - "build"
  - "Templates"
  - "scripts"
  - ".tuist-bin"
  - ".devxp"
  - "**/Generated"
  - "**/SwifterSwift"
  - "**/Dependencies"
  - "App"
  - "Project.swift"
  - "Tuist.swift"
  - "Package.swift"

opt_in_rules:
  - modifier_order
  - array_init
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - empty_string
  - explicit_init
  - fallthrough
  - fatal_error_message
  - first_where
  - identical_operands
  - let_var_whitespace
  - last_where
  - lower_acl_than_parent
  - pattern_matching_keywords
  - prohibited_super_call
  - redundant_nil_coalescing
  - single_test_class
  - sorted_first_last
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - yoda_condition

disabled_rules:
  - todo
  - orphaned_doc_comment
  - redundant_type_annotation
  - redundant_optional_initialization
  - number_separator
  - object_literal
  - file_name
  - sorted_imports
  - file_header
  - vertical_whitespace_opening_braces
  - vertical_whitespace_closing_braces
  - trailing_whitespace
  - blanket_disable_command
  - multiple_closures_with_trailing_closure

analyzer_rules:
  - unused_declaration
  - unused_import
  - typesafe_array_init

force_cast: warning
force_try: warning

line_length:
  warning: 300
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

function_body_length:
  warning: 60

type_body_length:
  warning: 300

file_length:
  warning: 600

function_parameter_count:
  warning: 7

legacy_hashing: error

identifier_name:
  excluded:
    - i
    - id
    - x
    - y
    - z
    - to
    - iO
    - vc
    - by

modifier_order:
  preferred_modifier_order:
    [
      override,
      acl,
      setterACL,
      dynamic,
      mutators,
      lazy,
      final,
      required,
      convenience,
      typeMethods,
      owned,
    ]

private_over_fileprivate:
  validate_extensions: true

vertical_whitespace:
  max_empty_lines: 1

nesting:
  type_level: 2
  function_level: 2

cyclomatic_complexity:
  warning: 30
  error: 40

large_tuple:
  warning: 3
  error: 4
